apiVersion: v2
name: lvm-localpv
description: CSI Driver for dynamic provisioning of LVM Persistent Local Volumes.
version: 1.7.0-develop
appVersion: 1.7.0-develop
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
home: https://openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - filesystem
  - LVM
  - Local Persistent Volumes
  - storage
sources:
- https://github.com/openebs/lvm-localpv
dependencies:
  - name: crds
    version: 1.7.0-develop
    condition: crds.enabled
